<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class InstanceCreation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required',
            'user_id' => 'required|exists:users,id',
            'configuration.bots' => 'required|integer|min:1|max:100000',
            'configuration.storage-size' => 'required|integer|min:0|max:1000',
            'configuration.storage-hash' => 'required|string|min:32|max:1024',
            'configuration.api' => 'required'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

}
